vich_uploader:
  db_driver: orm

  mappings:
    upload:
      uri_prefix: /front/upload
      upload_destination: '%kernel.project_dir%/public/front/upload'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer